### ISSUE TITLE
Sample table?

### ISSUE THREAD

**Issue by MostHated** [MacacaGames/DesignDataAgent#1]
Hey there,
    Do you happen to save a sample file that is working and can be opened with the editor window, just so I can see how the data is laid out?

Thanks,
-MH

-- Edit: Any chance you could add a license to this repo and OnionDataEditor as well? I like the editor, but mostly out of paranoia, I can't use anything in my projects without a license so that I know for sure it is ok to use. :+1:

**Comment by ttesttes93405** [comment]
Hi MostHated,

I've added a simple sample in `Sample01` folder. Hope to help you understand this project.
Also, a MIT license has been added to this repo and OnionDataEditor. Enjoy it!

Best wishes,
Owen

**Comment by MostHated** [comment]
Awesome, much appreciated.  ![](https://cdn4.iconfinder.com/data/icons/logos-brands-5/24/unity-16.png)
